<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
	xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
	<modelVersion>4.0.0</modelVersion>

	<groupId>com.joyzl</groupId>
	<artifactId>watcher</artifactId>
	<version>1.2.2</version>

	<name>JOYZL Watcher</name>
	<description>文档自动归集客户端工具软件</description>
	<url>https://github.com/JoyLinks/watcher</url>

	<properties>
		<maven.compiler.source>17</maven.compiler.source>
		<maven.compiler.target>17</maven.compiler.target>
		<project.build.sourceEncoding>UTF-8</project.build.sourceEncoding>
		<outputDirectory>publish/watcher</outputDirectory>
	</properties>

	<licenses>
		<license>
			<name>The Apache Software License, Version2.0</name>
			<url>https://www.apache.org/licenses/</url>
			<distribution>repo</distribution>
		</license>
	</licenses>

	<developers>
		<developer>
			<name>ZhangXi</name>
			<email>simon.zhang@msn.com</email>
			<organization>重庆骄智科技有限公司</organization>
			<organizationUrl>http://server.joyzl.com</organizationUrl>
		</developer>
	</developers>

	<dependencies>
		<dependency>
			<groupId>com.joyzl</groupId>
			<artifactId>network</artifactId>
			<version>3.1.16</version>
		</dependency>
		<dependency>
			<groupId>com.joyzl</groupId>
			<artifactId>backdoor</artifactId>
			<version>1.0.8</version>
		</dependency>
		<dependency>
			<groupId>com.joyzl</groupId>
			<artifactId>logger</artifactId>
			<version>3.1.2</version>
		</dependency>

		<dependency>
			<groupId>org.junit.jupiter</groupId>
			<artifactId>junit-jupiter</artifactId>
			<version>5.11.0</version>
			<scope>test</scope>
		</dependency>
	</dependencies>

	<build>
		<plugins>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-compiler-plugin</artifactId>
				<version>3.14.0</version>
				<configuration>
					<compilerArgs>
						<arg>--module-version=${project.version}</arg>
					</compilerArgs>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-jar-plugin</artifactId>
				<version>3.4.1</version>
				<configuration>
					<outputDirectory>${outputDirectory}/lib</outputDirectory>
					<archive>
						<manifest>
							<addDefaultImplementationEntries>true</addDefaultImplementationEntries>
							<addDefaultSpecificationEntries>true</addDefaultSpecificationEntries>
						</manifest>
						<manifestEntries>
							<Implementation-Version>${project.version}</Implementation-Version>
						</manifestEntries>
					</archive>
				</configuration>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-dependency-plugin</artifactId>
				<version>3.3.0</version>
				<configuration>
					<outputDirectory>${outputDirectory}/lib</outputDirectory>
					<includeScope>runtime</includeScope>
				</configuration>
				<executions>
					<execution>
						<id>copy-dependencies</id>
						<phase>package</phase>
						<goals>
							<goal>copy-dependencies</goal>
						</goals>
					</execution>
				</executions>
			</plugin>
			<plugin>
				<groupId>org.apache.maven.plugins</groupId>
				<artifactId>maven-resources-plugin</artifactId>
				<version>3.3.1</version>
				<executions>
					<execution>
						<phase>package</phase>
						<goals>
							<goal>copy-resources</goal>
						</goals>
						<configuration>
							<outputDirectory>${outputDirectory}</outputDirectory>
							<overwrite>true</overwrite>
							<resources>
								<resource>
									<directory>${basedir}/patterns</directory>
									<includes>
										<include>**/*</include>
									</includes>
									<filtering>false</filtering>
								</resource>
								<resource>
									<directory>${basedir}</directory>
									<includes>
										<include>watcher.properties</include>
										<include>readme.md</include>

										<include>watcher.ico</include>
										<include>service_windows-AMD64.exe</include>
										<include>service_windows-ARM64.exe</include>
										<include>service_windows-x86.exe</include>
										<include>install-desktop.ps1</include>
										<include>install-desktop.cmd</include>
										<include>install-service.ps1</include>
										<include>install-service.cmd</include>
										<include>uninstall.ps1</include>
										<include>uninstall.cmd</include>
										<include>update.ps1</include>

										<include>watcher.png</include>
										<include>install-desktop.sh</include>
										<include>install-service.sh</include>
										<include>uninstall.sh</include>
										<include>update.sh</include>
									</includes>
								</resource>
							</resources>
						</configuration>
					</execution>
				</executions>
			</plugin>
		</plugins>
	</build>
</project>