#JOYZL
#Sat Jun 13 17:00:02 CST 2026
LOG_EXPIRES=30
NUMBER=GP001
WATCH=D\:\\JOYZL SCADA DEMO\\test
HTTP_SERVER=http\://127.0.0.1/archive/file
STABLE_EXPIRES=3600
MODEL=patterns/ANY.xml
LOG_LEVEL=3
UPLOAD_EXPIRES=3600
UDP=23516